permalink: pretty

name: Review permissions
description: Protect your accounts in a few minutes, and a few clicks.

url: https://www.permissions.review

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - LICENSE
  - README.md
