---
- name: Google
  description: Gmail, Maps, Docs, YouTube, and more.
  url: https://www.google.com/
  review_url: https://myaccount.google.com/permissions
  docs_url: https://support.google.com/accounts/bin/answer/3466521

- name: Facebook
  description: Social network.
  url: https://www.facebook.com/
  review_url: https://www.facebook.com/settings?tab=applications

- name: Twitter
  description: Social network.
  url: https://twitter.com
  review_url: https://twitter.com/settings/applications
  docs_url: https://support.twitter.com/articles/76052

- name: Microsoft
  description: Outlook, Xbox, OneDrive, and more.
  url: https://www.microsoft.com
  review_url: https://account.live.com/consent/Manage

- name: LinkedIn
  description: Social network.
  url: https://www.linkedin.com
  review_url: https://www.linkedin.com/psettings/permitted-services

- name: Instagram
  description: Photo-sharing.
  url: https://www.instagram.com
  review_url: https://www.instagram.com/accounts/manage_access/

- name: Tumblr
  description: Microblogging.
  url: https://www.tumblr.com/
  review_url: https://www.tumblr.com/settings/apps

- name: Dropbox
  description: Cloud storage.
  url: https://www.dropbox.com/
  review_url: https://www.dropbox.com/account/connected_apps

- name: GitHub
  description: Hosting service for software development.
  url: https://github.com/
  review_url: https://github.com/settings/applications
  docs_url: https://help.github.com/articles/connecting-with-third-party-applications

- name: GitLab
  description: Code collaboration platform.
  url: https://gitlab.com/
  review_url: https://gitlab.com/profile/applications

- name: Reddit
  description: social news, and -media aggregation.
  url: https://www.reddit.com
  review_url: https://www.reddit.com/prefs/apps/

- name: Spotify
  description: Music streaming platform.
  url: https://www.spotify.com/
  review_url: https://www.spotify.com/account/apps/

- name: SoundCloud
  description: Music and audio streaming platform.
  url: https://soundcloud.com/
  review_url: https://soundcloud.com/settings/connections

- name: Medium
  description: Blog-publishing platform.
  url: https://medium.com/
  review_url: https://medium.com/me/applications

- name: Pocket
  description: Bookmarking.
  url: https://getpocket.com
  review_url: https://getpocket.com/connected_applications

- name: Vimeo
  description: Video hosting.
  url: https://vimeo.com
  review_url: https://vimeo.com/settings/apps

- name: Evernote
  description: Note-taking app.
  url: https://evernote.com/
  review_url: https://www.evernote.com/ConnectedServices.action

- name: Heroku
  description: Cloud platform-as-a-service
  url: https://www.heroku.com/
  review_url: https://dashboard.heroku.com/account/applications
- name: Slack
  description: Cloud-based team communication and collaboration.
  url: https://slack.com/
  review_url: https://blendle.slack.com/apps/manage
